Title = {
'Error_Item': 'Existing Item',
'Error_Espece': 'No species provided or invalid species',
'Error_Race': 'No breed provided',
'Error_Category': 'No category provided',
'Error_Rearing': 'No rearing method provided',
'Error_Coproduct': 'No coproduct provided',
'Error_Gompertz': 'No Gompertz coefficient provided',
'Error_EBW0': 'No Empty Body Weight at Birth',
'Error_EBWm': 'No Empty Body Weight at Maturity',
'Error_EBWsl': 'No Empty Body Weight at Slaughter Age',
'Error_FAT0': 'No Birth Body Fat Percentage',
'Error_FATm': 'No Normal Mature Body Fat Percentage',
'Error_FATmax': 'No Fat Percentage at Slaughter Age',
'Error_Rwp': 'No Ratio of Body Weight Water to Protein',
'Error_z1': 'No Protein Energy Content',
'Error_z2': 'No Protein Lipid Content',
'Error_act_coeff': 'No Coefficient for Activity Energy',
'Error_Carcass_Yield': 'No Carcass Yield'
}

Text = {
'Error_Item': 'This item already exists in the database',
'Error_Espece': 'You must fill the field "Species" or this field is invalid',
'Error_Race': 'You must fill the field "Breed"',
'Error_Category': 'You must fill the field "Category"',
'Error_Rearing': 'You must fill the field "Rearing Method"',
'Error_Coproduct': 'You must enter at least one coproduct in the table',
'Error_Gompertz': 'You must provide a Gompertz coefficient',
'Error_EBW0': 'You must provide a value for the Empty Body Weight at Birth',
'Error_EBWm': 'You must provide a value for the Empty Body Weight at Maturity',
'Error_EBWsl': 'You must provide a value for the Empty Body Weight at Slaughter Age',
'Error_FAT0': 'You must provide a value for the Birth Body Fat Percentage',
'Error_FATm': 'You must provide a value for the Normal Mature Body Fat Percentage',
'Error_FATm': 'You must provide a value for the Fat Percentage at Slaughter Age',
'Error_Rwp': 'You must provide a value for the Ratio of Body Weight Water to Protein',
'Error_z1': 'You must provide a value for the Protein Energy Content',
'Error_z2': 'You must provide a value for the Lipid Energy Content',
'Error_act_coeff': 'You must provide a value for the coefficient for Activity Energy',
'Error_Carcass_Yield': 'You must provide a value for the Carcass Yield'
}

Details = {
'Error_Item': 'You must change at leats one of the three characteristics (Breed, Category or Rearing Method)',
'Error_Espece': 'The species must be Bovine, Ovine or Calf',
'Error_Race': 'Examples: Charolaise, Limousine, etc.',
'Error_Category': 'Examples: Boeuf, Jeune Bovin, etc.',
'Error_Rearing': 'Examples: Pasture, Stall, etc.',
'Error_Coproduct': 'If you already entered coproducts, be sure to start at the first line and that your list has no break',
'Error_Gompertz': 'Recommended value for bovine: 0.012 ; for ovine: 0.03',
'Error_EBW0': 'Recommended value for bovine: 50 ; for ovine: 5',
'Error_EBWm': 'Recommended value for bovine: 1000 ; for ovine: 65',
'Error_EBWsl': 'Recommended value for bovine: 742 ; for ovine: 39 ; for calf: 252',
'Error_FAT0': 'Recommended value for bovine: 0.06 ; for ovine: 0.01',
'Error_FATm': 'Recommended value for bovine: 0.3 ; for ovine: 0.25',
'Error_FATmax': 'Recommended value for bovine: 0.45 ; for ovine: 0.33',
'Error_Rwp': 'Recommended value for bovine: 3 ; for ovine: 3.5',
'Error_z1': 'Recommended value: 55.352',
'Error_z2': 'Recommended value: 49.167',
'Error_act_coeff': 'Recommended value for bovine: 0.17 ; for ovine: 0.0107',
'Error_Carcass_Yield': 'Recommended value for bovine: 0.53 ; for ovine : 0.48'
}
